In [1]:
import pandas as pd
import numpy as np

In [2]:
codon_usage_df = pd.read_csv('G:\Miniconda Projects\Codon Usage Data Set\codon_usage.csv')

G:\Miniconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (5,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [71]:
codon_usage_df.head(-5)

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,virus,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,virus,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,virus,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.0218,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,virus,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,virus,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13018,primate,1,9597,2948,mitochondrion Pan paniscus,0.02171,0.03256,0.01832,0.00441,0.02001,...,0.00204,0.00034,0.00034,0.00475,0.02069,0.02205,0.00678,0.00237,0.00068,0.01934
13019,primate,0,9598,328023,Pan troglodytes,0.0138,0.022,0.00569,0.01047,0.01147,...,0.01214,0.01339,0.01351,0.01751,0.02667,0.02191,0.04283,0.00065,0.00060,0.00165
13020,primate,1,9598,3275,mitochondrion Pan troglodytes,0.0229,0.0287,0.01863,0.00275,0.01954,...,0.00092,0.00031,0.00031,0.00794,0.01924,0.02382,0.00580,0.00122,0.00214,0.01893
13021,primate,0,9600,96254,Pongo pygmaeus,0.01739,0.02236,0.00887,0.01221,0.01307,...,0.00885,0.01497,0.01232,0.01886,0.02383,0.02546,0.03319,0.00149,0.00068,0.00150
13022,primate,1,9600,2525,mitochondrion Pongo pygmaeus,0.01228,0.03446,0.01624,0.00752,0.01505,...,0.00079,0.00000,0.00040,0.00198,0.01941,0.02218,0.00792,0.00277,0.00079,0.01861

In [14]:
codon_usage_df.Kingdom.value_counts()

bct    2920
vrl    2832
pln    2523
vrt    2077
inv    1345
mam     572
phg     220
rod     215
pri     180
arc     126
plm      18
Name: Kingdom, dtype: int64

In [13]:
#Create Dictionary with full names for kingdom
full_name_dict = {'arc':'archaea', 'bct':'bacteria', 'phg':'bacteriophage',
                 'plm' :'plasmid', 'pln' :'plant', 'inv' :'invertebrate',
                 'vrt' :'vertebrate', 'mam' :'mammal', 'rod' :'rodent',
                 'pri' :'primate', 'vrl':'virus'}

In [17]:
codon_usage_df = codon_usage_df.replace({'Kingdom':full_name_dict})
codon_usage_df.Kingdom.value_counts()

bacteria         2920
virus            2832
plant            2523
vertebrate       2077
invertebrate     1345
mammal            572
bacteriophage     220
rodent            215
primate           180
archaea           126
plasmid            18
Name: Kingdom, dtype: int64

In [67]:
mean_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('mean').round())
median_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('median').round())
max_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('max').round())
min_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('min').round())

In [69]:
pd.concat([pd.Series(mean_dict, name='Mean'),
           pd.Series(median_dict, name='Median'),
           pd.Series(max_dict, name='Max'),
           pd.Series(min_dict, name='Min')],
           axis=1).astype(int)

                 Mean  Median       Max   Min
archaea        225434   12164   1420978  1050
bacteria       199353    6674   4100487  1000
bacteriophage   10251    2379    114247  1008
invertebrate    51478    3200  21945319  1000
mammal          19900    2815   5198458  1001
plant           61513    2360  34132283  1000
plasmid         12596   14924     28138  1164
primate        299360    2584  40662582  1025
rodent         156279    2279  24533776  1009
vertebrate      14457    2167   8042248  1007
virus           24992    2842  16473114  1001

In [83]:
# Create New mitochondrion DNA column
codon_usage_df['MitochondrionDNA'] = codon_usage_df.SpeciesName.str.contains('mitochondrion',regex=False)
codon_usage_df['MitochondrionDNA'].value_counts()

False    10129
True      2899
Name: MitochondrionDNA, dtype: int64

In [85]:
codon_usage_df['Kingdom'] = np.where(codon_usage_df['MitochondrionDNA'] == True, 'mitochondria', codon_usage_df['Kingdom'])

In [86]:
codon_usage_df.Kingdom.value_counts()

bacteria         2920
mitochondria     2899
virus            2832
plant            2371
invertebrate      934
vertebrate        464
bacteriophage     220
archaea           126
mammal            102
primate            83
rodent             59
plasmid            18
Name: Kingdom, dtype: int64

In [87]:
mean_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('mean').round())
median_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('median').round())
max_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('max').round())
min_dict = dict(codon_usage_df.groupby(['Kingdom'])['Ncodons'].agg('min').round())

pd.concat([pd.Series(mean_dict, name='Mean'),
           pd.Series(median_dict, name='Median'),
           pd.Series(max_dict, name='Max'),
           pd.Series(min_dict, name='Min')],
           axis=1).astype(int)

                 Mean  Median       Max   Min
archaea        225434   12164   1420978  1050
bacteria       199353    6674   4100487  1000
bacteriophage   10251    2379    114247  1008
invertebrate    71712    3492  21945319  1000
mammal          85131    2594   5198458  1001
mitochondria     7666    2388   8998998  1003
plant           64915    2192  34132283  1000
plasmid         12596   14924     28138  1164
primate        536318    2627  40662582  1033
rodent         554778    4210  24533776  1009
vertebrate      52335    2788   8042248  1009
virus           24992    2842  16473114  1001

In [88]:
codon_usage_df[codon_usage_df['Ncodons']<2000]

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA,MitochondrionDNA
0,virus,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000,False
1,virus,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000,False
3,virus,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000,False
35,virus,0,10373,1802,Macaca mulatta cytomegalovirus,0.00999,0.01498,0.00832,0.00999,0.01332,...,0.01387,0.01165,0.03496,0.02109,0.03108,0.04218,0.00111,0.00000,0.00166,False
36,virus,0,103782,1467,Pariacato virus,0.01909,0.01772,0.00682,0.01977,0.01022,...,0.00682,0.01227,0.02795,0.01977,0.02318,0.02999,0.00136,0.00000,0.00068,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13011,primate,0,9587,1181,Hylobates klossii,0.01439,0.02286,0.00254,0.01355,0.00762,...,0.01270,0.00931,0.01609,0.02286,0.02625,0.02794,0.00085,0.00085,0.00085,False
13012,primate,0,9589,1433,Hylobates pileatus,0.02303,0.02233,0.01186,0.01256,0.01605,...,0.01186,0.00628,0.01535,0.01256,0.02512,0.01396,0.00070,0.00140,0.00000,False
13014,mitochondria,1,9590,1387,mitochondrion Symphalangus syndactylus,0.02019,0.03749,0.01658,0.00216,0.02019,...,0.00072,0.00000,0.00433,0.02163,0.02235,0.00649,0.00144,0.00144,0.02307,True
13023,primate,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638,False
13025,mitochondria,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017,True